# Generated by Django 4.2.5 on 2023-09-29 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_link', models.CharField(max_length=600)),
                ('duration_in_seconds', models.IntegerField()),
                ('product', models.ManyToManyField(related_name='course', to='market.product')),
            ],
        ),
    ]
